### ISSUE TITLE
Increase NoteID clickable surface on search event

### ISSUE THREAD

**Issue by alltheseas** [darashi/nos.today#2]
_current UI_
![current](https://user-images.githubusercontent.com/64376233/229981193-8cf4a24d-1636-4282-af85-84bfbbc961e5.png)

_suggested UI_
![suggested](https://user-images.githubusercontent.com/64376233/229981161-a1fceebc-ca76-450b-8c57-78f35bd8de39.png)

_comments_
If note contains a URL, URL should be clickable and lead to URL destination (not noteID)

**Comment by darashi** [comment]
Okay, I will try it!

**Comment by darashi** [comment]
I think I got it. Is it implemented as intended?

**Comment by alltheseas** [comment]
> I think I got it. Is it implemented as intended?

✅
