### ISSUE TITLE
Add copy noteID & copy npub UI

### ISSUE THREAD

**Issue by alltheseas** [darashi/nos.today#3]
## User Story
As a nos.today search engine user who is collecting information, I would like a way to copy the noteID to clipboard, so that I can paste the noteID elsewhere & collect noteID of multiple events before I investigate each one in detail in my nostr client.

### Acceptance Criteria
1. Nos.today has a copy noteID button adjacent to each note
2. If user taps/clicks on copy noteID button, noteID is transposed to memory/clipboard

## User Story
As a nos.today search engine user who is collecting information, I would like a way to copy the npubs to clipboard, so that I can paste the npub elsewhere & collect npub of multiple users before I investigate each one in detail in my nostr client.

### Acceptance Criteria
1. Nos.today has a copy npub button adjacent to each note
2. If user taps/clicks on copy npub button, npub is transposed to memory/clipboard

_mockup_
Clearly I am not a designer 😂
![copy paste buttons](https://user-images.githubusercontent.com/64376233/230155662-235ce1ac-3191-4b15-86ac-9d0841e463a1.png)

**Comment by darashi** [comment]
Yes, I think I need this too. I will try it. It would require one extra click, but maybe we could add a 3-dot menu and choose from there.

**Comment by darashi** [comment]
Just Implemented. Maybe more refinement might be needed...

**Comment by darashi** [comment]
I tried but the drop down menu was overkill at this point so I stopped. Just two buttons are placed.

**Comment by darashi** [comment]
As you say, it is confusing on a small screen. I adjusted the margins, though there may be a better way.

**Comment by alltheseas** [comment]
Would it be strange looking to always have the copy note button on the bottom right of the note?
