### ISSUE TITLE
Permalink to specific search string 

### ISSUE THREAD

**Issue by dergigi** [darashi/nos.today#6]
It would be great if you could link to specific searches, like this:

- `https://nos.today/?q=foo`

I find myself in the situation where I want to link to certain generic thing on nostr, mostly search strings and/or hashtags. 

---

Not sure what the prefix should be, here is how various search engines do it:

- `https://www.google.com/search?q=foo`
- `https://duckduckgo.com/?q=foo`
- `https://nostrview.com/search?q=foo`

URL param `q` as part of query string seems to be the default. Personally I would like something like `nos.today/q/foo` more (or even `/s/foo`), but that's probably just me.

**Comment by darashi** [comment]
Thanks for the feedback. Yes, it should have! Hard to decide on the path, though.

I too think a path without query parameters would be cool, but I had some trouble when I built a similar system (I don't remember exactly, but handling slashes for example). So I think I'll go with `/?q=foo` or `/search?q=foo`.  I'll give it a try when I have time.

**Comment by darashi** [comment]
I think I've done it, with `/search?q=foo` style path. Is it working as you expected? :smiley:
