### ISSUE TITLE
Concerns with HTML Tag Handling

### ISSUE THREAD

**Issue by erechorse** [darashi/nos.today#9]
There are concerns regarding HTML tag handling in the nos.today. While the security aspect appears to be satisfactory, there is a possibility of unintended behavior. This includes the risk of XSS attacks and the potential for unexpected outcomes when linking to external resources.

like this:

![marquee demo](https://github.com/darashi/nos.today/assets/55797122/5f4df1ea-9e95-4296-990a-7567f4c264c2)

**Comment by darashi** [comment]
Thanks for your feedback.

nos.today uses DOMPurify to filter out problematic tags (and attributes):
https://github.com/darashi/nos.today/blob/ba8e4a251bd076f7dbe4b2938705b04fc3c08629/src/app/search/NoteContent.tsx#L44-L47

So, I believe XSS is being prevented as long as DOMPurify is implemented correctly and I'm using it in the right way. The video seems to be using the MARQUEE tag, not unintended "script execution".

I didn't get what situation you meant by "unexpected outcomes when linking to external resources". Can you provide an example of what situation you are concerned about?

That being said, I think you're right that this implementation doesn't make good sense, and if you mean that it's not following NIP-01, which strongly argues that `content` is not Markdown, then I agree completely. It should be fixed.

**Comment by erechorse** [comment]
My concern about the external link was a meander. It seems that a strange context was inserted after machine translation, so you can ignore it.
Other than that, I completely agree with you. Thanks for interpreting my poor bug report so well.

**Comment by darashi** [comment]
Now deploied. It should work as expected, and no longer marquee runs 😁
